blueprint:
  name: Tuya TS0041 1-Button Scene Switch (Zigbee2MQTT)
  description: >
    Automate your Tuya TS0041 1-Button Scene Switch using Zigbee2MQTT.
    Supports single, double, and long press actions via MQTT.
    Optimized for better maintainability and functionality.
    Version: 20250507
  domain: automation
  input:
    remote_name:
      name: (Zigbee2MQTT) Remote Name
      description: The name of the switch in Zigbee2MQTT (e.g. tuya_button_1)
      selector:
        text:
    base_topic:
      name: (Zigbee2MQTT) Base MQTT Topic
      description: Usually 'zigbee2mqtt'
      default: zigbee2mqtt
      selector:
        text:
    button_single_press:
      name: Button - Single Press
      default: []
      selector:
        action: {}
    button_double_press:
      name: Button - Double Press
      default: []
      selector:
        action: {}
    button_long_press:
      name: Button - Long Press
      default: []
      selector:
        action: {}

  source_url: https://github.com/Moselmann/homeassistant/blob/main/blueprints/zigbee2mqtt_smart_1_button_scene_switch_ts0041.yaml

mode: queued
max_exceeded: silent

trigger_variables:
  z2m_base_topic: !input base_topic
  z2m_controller: !input remote_name

trigger:
  - platform: mqtt
    topic: '{{ z2m_base_topic ~ "/" ~ z2m_controller ~ "/action" }}'
    id: button-press

action:
  - variables:
      z2m_base_topic: !input base_topic
      z2m_controller: !input remote_name

  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.payload == "single" }}'
        sequence: !input button_single_press

      - conditions:
          - condition: template
            value_template: '{{ trigger.payload == "double" }}'
        sequence: !input button_double_press

      - conditions:
          - condition: template
            value_template: '{{ trigger.payload == "hold" }}'
        sequence: !input button_long_press
